# Reference: https://build-cpp.github.io/cmkr/cmake-toml
[project]
name = "Remill-X86"

[find-package.LLVM]
required = true
config = true
[find-package.Clang]
required = true
config = true

[target.Remill-X86-bin]
type = "executable"
sources = ["src/tool/**.cpp", "src/tool/**.h"]
include-directories = ["${LLVM_INCLUDE_DIRS}", "${CLANG_INCLUDE_DIRS}"]
link-directories = ["${LLVM_LIBRARY_DIRS}", "${CLANG_LIBRARY_DIRS}"]
add-definitions = ["${LLVM_DEFINITIONS}", "${CLANG_DEFINITIONS}"]
link-libraries = [
"LLVMSupport", 
"LLVMAnalysis",
"LLVMCore",
"LLVMCodeGen"
]

